##Definimos el nombre del workflow como "CI Pipeline" y especificamos que se ejecute en eventos de push y pull request en la rama main.
name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
##Definimos un trabajo llamado "build" que se ejecutará en un entorno de Ubuntu. Este trabajo consta de varios pasos, incluyendo la clonación del repositorio, la construcción de la imagen Docker de la aplicación y la ejecución de un test básico para verificar que la imagen se ha construido correctamente.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build Docker Imagene
        run: |
          docker build -t myapp:latest ./app
      - name: test basico
        run: echo "Simulando test basico para verificar que la imagen se ha construido correctamente"